services:
     - type: web
       name: telegram-bot
       env: python
       buildCommand: pip install -r requirements.txt
       startCommand: ai_bot_tg_4.py
       envVars:
         - key: PYTHON_VERSION
           value: 3.9.0
         - key: TG_TOKEN
           sync: false
         - key: TOGETHER_API_KEY
           sync: false